spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              # metadata-uri: https://dev-17700857.okta.com/app/exk9dn29foO7sxMqs5d7/sso/saml/metadata
              metadata-uri: https://dev-12009963.okta.com/app/exk9zzi2cxkB2P7Xd5d7/sso/saml/metadata
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
